name: SonarQube check

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ${{github.workspace}}/.sonar
          key: ${{ runner.os }}-sonar
      - name: Analyze with SonarQube
        uses: docker://sonarsource/sonar-scanner-cli:latest
        env:
          SONAR_USER_HOME: ${{github.workspace}}/.sonar
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://jacek.eu.ngrok.io
      - name: Echo workspace
        run: ls -la
      - name: Echo .sonar
        run: ls -la .sonar
#       - name: Check Quality Gate
#         uses: SonarSource/sonarqube-quality-gate-action@master
#         env:
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#         timeout-minutes: 5
